### ISSUE TITLE
[NG] Loramoduleをシリアル通信で、設定を書き込む。

### ISSUE THREAD

**Issue by kadu0922** [kadu0922/arduino#16]
## やること
シリアル通信で設定を１から書き込んで、通信できるように持っていく。
zコマンドで通信できるようにすればいいと思う

こっちは大変そう

## memo 
![image](https://user-images.githubusercontent.com/58362633/100498491-e669f280-31a5-11eb-98a1-fbdf65fbc549.png)
これと、評価ボードのピンアサインが対応してる

**Comment by kadu0922** [comment]
設定値
![image](https://user-images.githubusercontent.com/58362633/100832179-b6269a80-34aa-11eb-9df2-25fea7940c54.png)

**Comment by Setuna-git** [comment]
設定内容 | 送信 | 受信 | 送信 | 受信
-- | -- | -- | -- | --
ノード種別設定 | Coordinator | EndDevice | Coordinator | EndDevice
拡散率設定 | 11 | 12
無線チャンネル設定 | 7 | 1
自動送信データ設定 | 「b」を50個 | 「a」を50個

**Comment by Setuna-git** [comment]
設定内容 | 送信 | 受信
-- | -- | --
ノード種別設定 | Coordinator | EndDevice
拡散率設定 | 12
無線チャンネル設定 | 1
自動送信データ設定 | 1234567890(10個)
PANID | 0002
Own   Node ID |  
  |  
  |

**Comment by Setuna-git** [comment]
設定内容 | シリアル通信
-- | --
ノード種別設定 | Coordinator
帯域幅 | 250
拡散率設定 | 12
無線チャンネル設定 | 1
PAN   ネットワークアドレス設定 | 0002
自ノードネットワークアドレス設定 | 0012
送信先ノードネットワークアドレス設定 | 1012
Acknowledge   使用設定 | OFF
受信電波強度(RSSI)付与設定  | ON
動作モード設定 | Config
UART   転送速度 | 115200
自動送信間隔設定 | 5
自動送信データ設定 | 1234567890(10個)

**Comment by Setuna-git** [comment]
配線画像
![image](https://user-images.githubusercontent.com/31153352/100974550-c78da680-357f-11eb-82dc-f14cdb263b1c.png)

**Comment by Setuna-git** [comment]
参考サイト
https://ta2mi.hatenablog.com/entry/2019/10/07/171134

**Comment by Setuna-git** [comment]
# memo 
## configmodeで設定するコードを絶対にES920LRに流さないつぶれるためプロセッサモードで設定する！！
- ES920LRをTera Termなどで捜査したならArduinoと一度切り離す必要がある
- **ES920EBをUSB_PではなくBATTにする**
![image](https://user-images.githubusercontent.com/31153352/100983830-345b6d80-358d-11eb-840e-bfcf381fb30c.png)

**Comment by Setuna-git** [comment]
# 参考サイト
https://ta2mi.hatenablog.com/entry/2019/10/07/171134

**Comment by kadu0922** [comment]
ヘッダーとか抜きでもっかい作る
